### ISSUE TITLE
Run attitude_flyer.py encounter Error no LogEntry to handle id while connected crazydio pa with bitcraze vm

### ISSUE THREAD

**Issue by polarbeargo** [udacity/FCND-Controls-Crazyflie#1]
Hello @adrnp ,

I am a udacity Flying car student. I want to say thank you for the remarkable drone integration projects first! 

  Recently after I flash the crazyflie firmware, I'm run attitude_flyer.py on bitcraze vm with crazyradio PA connected to radio://0/80/2M encounter error log like bellow at the same time I can see the front left LED(4) is flickering shows radio connected but my crazyflie with Flow Deck didn't take off not sure what I'm missing here any help will be very appreciate.
![screenshot 36](https://user-images.githubusercontent.com/8589224/54027841-dc3bdf80-41dd-11e9-9f72-5022133ae537.png)

**Comment by cptanalatriste** [comment]
Same here, I'm trying to run the controller in the solution branch and it's not working for me. The output is the following:

```
(crazyflie) cgc87@cgc87-Precision-7760:~/github/FCND-Controls-Crazyflie$ python attitude_flyer.py --uri radio://0/80/2M
Logs/TLog.txt
Logs/NavLog.txt
starting connection
Error no LogEntry to handle id=1
Error no LogEntry to handle id=2
arming transition
takeoff transition
Setting Home
waypoint transition
target position [0.0, 0.0, -0.5]
Traceback (most recent call last):
  File "attitude_flyer.py", line 321, in <module>
    drone.start()
  File "attitude_flyer.py", line 298, in start
    super().start()
  File "/home/cgc87/anaconda3/envs/crazyflie/lib/python3.7/site-packages/udacidrone/drone.py", line 534, in start
    self.connection.start()
  File "/home/cgc87/anaconda3/envs/crazyflie/lib/python3.7/site-packages/udacidrone/connection/crazyflie_connection.py", line 210, in start
    self._reset_position_estimator()
  File "/home/cgc87/anaconda3/envs/crazyflie/lib/python3.7/site-packages/udacidrone/connection/crazyflie_connection.py", line 483, in _reset_position_estimator
    self._scf.cf.param.set_value('kalman.resetEstimation', '1')
  File "/home/cgc87/anaconda3/envs/crazyflie/lib/python3.7/site-packages/cflib/crazyflie/param.py", line 320, in set_value
    raise Exception('Connection timed out')
Exception: Connection timed out

```

I also posted a question in Udacity's knowledge centre: https://knowledge.udacity.com/questions/861167
